[package]
name = "authz"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
common = { path = "../common" }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[features]
default = ["sourcehub"]
sourcehub = []
test-helpers = []

[dev-dependencies]
tokio = { workspace = true, features = ["full", "process"] }
serial_test = "3.2.0"
did-key = { workspace = true }

[lints]
workspace = true
