[package]
name = "authz"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
thiserror = { workspace = true }
common = { path = "../common" }
async-trait = "0.1"

[dev-dependencies]
tokio = { workspace = true, features = ["full", "process"] }
serial_test = "3.2.0"