use crate::error::{CryptoError, Result};
use std::fmt::Debug;
use zeroize::Zeroize;

/// A share distributed by one participant to another
#[derive(Clone)]
pub struct DistributedShare<ShareValue: Zeroize> {
    pub from_id: u32,
    pub to_id: u32,
    pub value: ShareValue,
    pub nonce: [u8; 16],  // Nonce to prevent replay attacks
    pub session_id: u128, // Session ID to prevent replay attacks
}

impl<ShareValue: Zeroize> Drop for DistributedShare<ShareValue> {
    fn drop(&mut self) {
        self.value.zeroize();
    }
}

// Manual impl (rather than derive) so the secret `value` field can never be printed,
// including by types that embed a ShareValue whose own Debug impl prints its bytes.
impl<ShareValue: Zeroize> Debug for DistributedShare<ShareValue> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("DistributedShare")
            .field("from_id", &self.from_id)
            .field("to_id", &self.to_id)
            .field("value", &"[REDACTED]")
            .field("nonce", &self.nonce)
            .field("session_id", &self.session_id)
            .finish()
    }
}

/// Private share containing an index and a scalar value
#[derive(Clone)]
pub struct PriShare<ShareValue: Zeroize> {
    pub i: u32,
    pub v: ShareValue,
}

impl<ShareValue: Zeroize> Drop for PriShare<ShareValue> {
    fn drop(&mut self) {
        self.v.zeroize();
    }
}

// Manual impl (rather than derive) so the secret scalar `v` can never be printed.
impl<ShareValue: Zeroize> Debug for PriShare<ShareValue> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PriShare")
            .field("i", &self.i)
            .field("v", &"[REDACTED]")
            .finish()
    }
}

/// Public share containing an index and a point value
#[derive(Clone, Debug)]
pub struct PubShare<PublicKey> {
    pub i: u32,
    pub v: PublicKey,
}

pub type SigShare<G> = PubShare<G>;

/// Distributed key share
#[derive(Clone)]
pub struct DistKeyShare<ShareValue: Zeroize> {
    pub pri_share: PriShare<ShareValue>,
}

impl<ShareValue: Zeroize> Drop for DistKeyShare<ShareValue> {
    fn drop(&mut self) {
        self.pri_share.v.zeroize();
    }
}

// Manual impl (rather than derive) for clarity: relies on PriShare's own redacting
// Debug impl, so the secret scalar can never be printed.
impl<ShareValue: Zeroize> Debug for DistKeyShare<ShareValue> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("DistKeyShare")
            .field("pri_share", &self.pri_share)
            .finish()
    }
}

/// Secret structure
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct Secret {
    pub enc_cmt: Vec<u8>,        // rG - Schnorr commitment
    pub encrypted_data: Vec<u8>, // AES-GCM encrypted data
    pub nonce: Vec<u8>,          // AES-GCM nonce (12 bytes)
}

/// Schnorr proof of knowledge of the encryption randomness `r` for `U = r*G`,
/// with the [`crate::context::CiphertextContext`] digest and the ciphertext
/// digest bound into the Fiat-Shamir challenge.
///
/// This proves the encryptor knew `r` and commits them to exactly one
/// `(ring_pk, policy fields, salt)` context and one `(nonce, ciphertext)` pair.
/// It intentionally does **not** prove the KEM was performed against the ring
/// key (a malformed document simply fails to decrypt via the threshold flow),
/// and it never carries the KEM shared secret.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct EncryptionProof {
    /// Fiat-Shamir challenge scalar, serialized.
    pub challenge: Vec<u8>,
    /// Proof response `z = k + c*r`, serialized.
    pub response: Vec<u8>,
}

impl TryFrom<String> for EncryptionProof {
    type Error = CryptoError;

    fn try_from(string: String) -> Result<Self> {
        serde_json::from_str(&string).map_err(|e| CryptoError::ParseError(e.to_string()))
    }
}

/// Schnorr proof of knowledge of `rdr_sk` for `rdr_pk = rdr_sk*G`.
///
/// Generated by the reader (never by a PRE node) and submitted alongside
/// `rdr_pk` in a PRE request. `reencrypt` verifies it before doing anything with
/// `rdr_pk`: without this, `rdr_pk` is only checked for group membership, and
/// `xnc_ski = ski*(rdr_pk + enc_cmt)` is linear in `rdr_pk` — an attacker
/// authorized for ciphertext A can submit `rdr_pk = U_B - U_A` (ordinary point
/// subtraction of two published commitments, no discrete log required) to
/// redirect the recovered commitment to `s*U_B`, ciphertext B's own KEM shared
/// point, without ever being authorized for B. This proof closes that gap: a
/// difference of two valid commitments is a valid point, but not one whose
/// discrete log the submitter can produce a proof for.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct ReaderKeyProof {
    /// Fiat-Shamir challenge scalar, serialized.
    pub challenge: Vec<u8>,
    /// Proof response `z = k + c*rdr_sk`, serialized.
    pub response: Vec<u8>,
}

impl TryFrom<EncryptionProof> for String {
    type Error = CryptoError;

    fn try_from(proof: EncryptionProof) -> Result<Self> {
        serde_json::to_string(&proof).map_err(|e| CryptoError::ParseError(e.to_string()))
    }
}

/// A PET tag ciphertext: `R = r_tag*G` and `T = F(owner_id) + r_tag*pet_pk`.
///
/// Produced by the tag producer (Bankd) under the ring's authoritative PET
/// public key, using encryption randomness (`r_tag`) independent from the
/// payload's own. Both components are bound into the [`TagKnowledgeProof`]
/// transcript; see [`crate::pet_context::tag_proof_digest`].
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct PetTag {
    pub ephemeral_point: Vec<u8>,
    pub masked_fingerprint: Vec<u8>,
}

/// Schnorr proof of knowledge of `r_tag` for `PetTag::ephemeral_point = r_tag*G`.
///
/// Its Fiat-Shamir transcript binds both tag components, the authoritative PET
/// public key and ring identity, and the complete payload envelope (ciphertext,
/// its policy/ring context, and its own [`EncryptionProof`]) — see
/// [`crate::pet_context::tag_proof_digest`]. Generated once by the encryptor;
/// every PET participant reconstructs the digest and verifies this proof
/// before joining PET.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct TagKnowledgeProof {
    /// Fiat-Shamir challenge scalar, serialized.
    pub challenge: Vec<u8>,
    /// Proof response `z = k + c*r_tag`, serialized.
    pub response: Vec<u8>,
}

/// Re-encryption reply
#[derive(Clone, Debug)]
pub struct ReencryptReply<ShareValue: Zeroize, PublicKey> {
    pub share: PubShare<PublicKey>,
    pub challenge: ShareValue,
    pub proof: ShareValue,
}

impl<ShareValue: Zeroize, PublicKey> Drop for ReencryptReply<ShareValue, PublicKey> {
    fn drop(&mut self) {
        self.challenge.zeroize();
        self.proof.zeroize();
    }
}
