[package]
name = "jubjub-wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
jubjub = { version = "0.11.1", features = ["zeroize"] }
group = "0.14"
sha2 = "0.10"

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
