[package]
name = "authn"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
did-key = "0.2.1"
thiserror = { workspace = true }
# Enable alloc feature to fix form_urlencoded compatibility with did-key
form_urlencoded = { workspace = true }
