[package]
name = "authn"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
did-key = { workspace = true }
thiserror = { workspace = true }
form_urlencoded = { workspace = true }
serde = { workspace = true }
jsonwebtoken = "9"
pkcs8 = { version = "0.10.2", features = ["alloc"] }
tonic = { workspace = true }
zeroize = { workspace = true }
sha2 = { workspace = true }
rand = { workspace = true }

[lints]
workspace = true
