[package]
name = "authn"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
did-key = { workspace = true }
thiserror = { workspace = true }
form_urlencoded = { workspace = true }
serde = { workspace = true }
jsonwebtoken = "9"
jwt-simple = { version = "0.12", default-features = false, features = ["pure-rust"] }
tonic = "0.14.2"
