[package]
name = "crypto"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
ark-bls12-381 = "0.4"
ark-ec = "0.4"
ark-ff = "0.4"
ark-std = "0.4"
ark-serialize = "0.4"
rand = "0.8"
rand_core = "0.6"
subtle = "2.5"
sha2 = "0.10"
aes-gcm = "0.10"
hkdf = "0.12"