[package]
name = "crypto"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true


[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
zeroize = { workspace = true }
ark-bls12-381 = { version = "0.4", optional = true }
decaf377 = { version = "0.10", optional = true }
poseidon377 = { version = "1", optional = true }
ark-ec = "0.4"
ark-ff = "0.4"
ark-std = "0.4"
ark-serialize = "0.4"
rand = "0.8"
rand_core = "0.6"
subtle = "2.5"
sha2 = "0.10"
aes-gcm = "0.10"
hkdf = "0.12"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[features]
default = ["bls12-381"]
test-helpers = []
bls12-381 = ["dep:ark-bls12-381"]
decaf377 = ["dep:decaf377", "dep:poseidon377"]

[[bench]]
name = "pre_benchmarks"
harness = false
required-features = ["test-helpers"]

[[bench]]
name = "dkg_benchmarks"
harness = false
required-features = ["test-helpers"]

[[bench]]
name = "sign_benchmarks"
harness = false
required-features = ["test-helpers"]

[lints]
workspace = true
