name: Rust

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update Rust stable
      run: rustup update stable
    - name: Install protoc
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Install cargo-deny
      run: cargo install cargo-deny --locked
    - name: Check licences
      run: cargo deny check

  clippy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - crypto: bls12-381
            cargo_flags: --features=integration-test,fault-injection,scale-testing
          - crypto: decaf377
            cargo_flags: --no-default-features --features=decaf377,redb,integration-test,fault-injection,scale-testing
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Update Rust stable
      run: rustup update stable
    - name: Install protoc
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
    - name: Clippy (${{ matrix.crypto }})
      run: cargo clippy --all-targets ${{ matrix.cargo_flags }} -- -D warnings

  build:
    runs-on: runs-on=${{ github.run_id }}-${{ github.run_attempt }}-${{ strategy.job-index }}/\
      spot=pco/cpu=16+32/family=c6*+c7*/disk=large/extras=s3-cache
    strategy:
      fail-fast: false
      matrix:
        include:
          - crypto: bls12-381
            cargo_flags: --features=integration-test,fault-injection,scale-testing
          - crypto: decaf377
            cargo_flags: --no-default-features --features=decaf377,redb,integration-test,fault-injection,scale-testing
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Update Rust stable
      run: rustup update stable
    - name: Install protoc
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
    - name: Run tests (${{ matrix.crypto }})
      run: cargo test ${{ matrix.cargo_flags }} --verbose
